Fix missing cert-manager api-version.
Fixes the following error.

```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2
```